title: "Quynh The Nguyen"
author: "Quynh The Nguyen"
description: "Massachusetts Insitute of Technology"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "CV_QuynhNguyen.pdf", title: "CV"}
  - {title: "Research", file: "research.md"}
  - {file: "blog.md", title: "Blog"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:nguyentq@mit.edu"}
  - {title: Scholar, icon: mortar-board, url: "https://scholar.google.com/citations?view_op=list_works&hl=en&user=vTYawOEAAAAJ"}
  - {title: Github, icon: github, url: "https://github.com/nguyentq7"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/nguyentq7"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
